:imagesdir: ../assets/images

[#service-binding]
== Service Binding の詳細

Service Binding を使用すると、接続の詳細とシークレットをアプリケーションに伝えて、アプリケーションがサービスにバインドできるようにすることができます。 このコンテキストでは、サービスとは、Kafka インスタンス、NoSQL データベースなど、あらゆるものにすることができます。Service Binding を使用すると、接続の詳細 (ホスト、ポート)、認証メカニズム (SASL、OAuth)、資格情報 (ユーザー名/パスワード、クライアント ID/クライアント シークレット)  をアプリケーションに構成する必要がなくなります。代わりに、Service Binding は、アプリケーションが使用できるように、これらの変数をアプリケーション コンテナーに (ファイルまたは環境変数として) 挿入します。 Quarkus Kubernetes Service Binding 拡張機能を使用すると、Quarkus アプリケーションがファイルとして挿入されたこれらの変数をコンテナのファイルシステムから自動的に取得できるようになり、アプリケーション リソース (構成ファイルなど) 自体で構成設定を指定する必要がなくなります。

(参考) https://servicebinding.io/[Service Binding For Kubernetes ,role=external,window=_blank] 

<< <<add-event-streaming.adoc#event-goals, back to instructions>>


[#kafka-params]
== Kafka topic の設定パラメータの詳細

* パーティションは、トピック内のメッセージの個別のリストであり、トピックの一部をクラスター内の複数のブローカーに分散できるようにします。 トピックには 1 つ以上のパーティションを含めることができ、プロデューサーとコンシューマーの負荷をスケーリングできます。
* レプリカは、トピック内のパーティションのコピーです。 パーティション レプリカはクラスター内の複数のブローカーに分散され、ブローカーに障害が発生した場合でもトピックの可用性を確保します。 フォロワー レプリカがパーティション リーダーと同期している場合、必要に応じて、フォロワー レプリカが新しいパーティション リーダーになることができます。
* メッセージ保持時間は、クリーンアップ ポリシーに応じて、メッセージが削除または圧縮されるまでトピック内に保持される時間です。 保持サイズは、パーティション内のすべてのログ セグメントが削除または圧縮される前の最大合計サイズです。 このワークショップでは、デフォルト値をそのまま使用できます。

<< <<add-event-streaming.adoc#kafka-params, back to instructions>>
